import Image1 from "../../assets/blog-1.svg";

const blogCardData = [
    {
        id: 1,
        category: "Tech",
        thumbnail: Image1,
        title: "5 Best App Development Tools for your Projects",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 2,
        category: "Akash",
        thumbnail: Image1,
        title: "10 daily tasks to do",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 3,
        category: "Akash",
        thumbnail: Image1,
        title: "Understand view model in detail",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 4,
        category: "Akash",
        thumbnail: Image1,
        title: "9 things to do daily morning",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 5,
        category: "Akash",
        thumbnail: Image1,
        title: "How to start a startup?",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 6,
        category: "Akash",
        thumbnail: Image1,
        title: "Deep dive into coroutines and threads",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 7,
        category: "Akash",
        thumbnail: Image1,
        title: "Funny things that happened in my life",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 8,
        category: "Akash",
        thumbnail: Image1,
        title: "Sun rises in the east every morning",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 9,
        category: "Akash",
        thumbnail: Image1,
        title: "How to make a blog website using CMS",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
    {
        id: 10,
        category: "Akash",
        thumbnail: Image1,
        title: "How I met your mother",
        date: "24 March, 2023",
        author: "Akash Murugesh",
        url: "https://www.medium.com/",
    },
];

export default blogCardData;
